name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the documentation
          required: true
        - label: This feature would benefit the community, not just my specific use case
          required: true

  - type: textarea
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Have you considered any alternatives?

  - type: dropdown
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Theme Management
        - Security & Validation
        - Performance & Optimization
        - User Interface
        - API & Integration
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Needed for project completion
        - Critical - Blocking current work
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: |
        1. When using the theme manager to...
        2. When developers need to...
        3. When administering themes in...

  - type: textarea
    attributes:
      label: Example Implementation
      description: If you have ideas about how this could be implemented, share them here
      placeholder: |
        ```php
        // Example of how this feature might work
        $themeManager->newFeature();
        ```

  - type: checkboxes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature would introduce breaking changes
        - label: This feature could be implemented without breaking changes
        - label: I'm not sure about breaking changes

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might help...

  - type: checkboxes
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation for this feature